development:
  adapter: mysql2
  database: ddb_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: ddb_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: ddb_production
  username: root
  password: 
  encoding: utf8
